// <auto-generated />
using System;
using Delivery.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Delivery.Infrastructure.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    [Migration("20251011174407_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Delivery.Infrastructure.Models.DeliveryOrderModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssignedVehicleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedVehicleId");

                    b.HasIndex("PackageId");

                    b.ToTable("DeliveryOrders");
                });

            modelBuilder.Entity("Delivery.Infrastructure.Models.PackageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFragile")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("FuelConsumption")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxLoadKg")
                        .HasColumnType("REAL");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DroneModel", b =>
                {
                    b.HasBaseType("VehicleModel");

                    b.Property<double>("BatteryLevel")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxAltitudeMeters")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxFlightTimeMinutes")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxPayloadKg")
                        .HasColumnType("REAL");

                    b.ToTable("Drones", (string)null);
                });

            modelBuilder.Entity("TruckModel", b =>
                {
                    b.HasBaseType("VehicleModel");

                    b.Property<bool>("HasRefrigeration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfAxles")
                        .HasColumnType("INTEGER");

                    b.ToTable("Trucks", (string)null);
                });

            modelBuilder.Entity("Delivery.Infrastructure.Models.DeliveryOrderModel", b =>
                {
                    b.HasOne("VehicleModel", "AssignedVehicle")
                        .WithMany()
                        .HasForeignKey("AssignedVehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Delivery.Infrastructure.Models.PackageModel", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedVehicle");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("DroneModel", b =>
                {
                    b.HasOne("VehicleModel", null)
                        .WithOne()
                        .HasForeignKey("DroneModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TruckModel", b =>
                {
                    b.HasOne("VehicleModel", null)
                        .WithOne()
                        .HasForeignKey("TruckModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
